trigger: 
  branches:
    include:
    - master
  paths:
   include:
     - app/*
     - app/RKST Base.de-AT.g.xlf
   exclude:
     - app/app.json

resources:
  repositories:
    - repository: templates
      type: git
      name: Template/Yaml-PipelineTemplate

extends:
    template: Build_OnPremise.yml@templates
    parameters:
      BuildVersion: $(BuildVersion)