# Es wird das Compiler.Zip benötigt,
trigger: 
- none

resources:
  repositories:
    - repository: templates
      type: git
      name: Template/Yaml-PipelineTemplate

extends:
    template: Build_OnPremise.yml@templates
    parameters:
      BuildVersion: $(BuildVersion)
